### ISSUE TITLE
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and

### ISSUE THREAD

**Issue by tseemann** [TimoLassmann/kalign#12]
`autogen.sh` prints this
```
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
```
not really a bug but thought i should report it anyway

**Comment by TimoLassmann** [comment]
Hmm, I had 'AC_CONFIG_MACRO_DIRS([m4])' in configure.ac - notice the 'S'. Changed this now - and thanks again for reporting this and the other issues!
