### ISSUE TITLE
tagged releases for 2.3.4 and 2.3.5

### ISSUE THREAD

**Issue by mr-c** [TimoLassmann/kalign#21]
Hello, I just noticed that the development branch has 2.3.5 in it, but there is no tagged release for 2.3.4 nor 2.3.5; which is why we didn't notice and update the Debian package. 

So if you intended those versions for users, then please make tagged releases. Thanks!

**Comment by TimoLassmann** [comment]
There is now a new 3.3 tagged release.

**Comment by mr-c** [comment]
Thanks @TimoLassmann !
