### ISSUE TITLE
Choose the number of threads

### ISSUE THREAD

**Issue by ATVincent** [TimoLassmann/kalign#24]
Hello,

Is there a way to choose the number of threads? It seems that changing the OMP_NUM_THREADS environment variable doesn't work and there is no argument.

Thank you,

Antony

**Comment by TimoLassmann** [comment]
Hi Anthony,

There is an hidden option "-nthreads" to set the number of threads. However, kalign uses nested parallelism and therefore ends up using more threads during the tree building and alignment stage. This is not nice at all and I'll have to fix this soon.

In the meantime, if you want to limit kalign to use a maximum of e.g. 8 threads, set the OMP_NUM_THREADS to 8 and use the -nthreads 8 option.

Cheers, Timo
