### ISSUE TITLE
number of threads

### ISSUE THREAD

**Issue by ardy20** [TimoLassmann/kalign#28]
Hi
How many cpus it use? How can we increase number of threads or CPU when using clusters?

**Comment by xizhihui** [comment]
https://github.com/TimoLassmann/kalign/blob/d494b4ce715cf0907db1bc57d0d5ddaf6f382b10/src/run_kalign.c#L208

so use "-n number".

**Comment by TimoLassmann** [comment]
In version 3.3.4 this can be set using the -nthreads option.
