### ISSUE TITLE
how to adjust the penalty parameter

### ISSUE THREAD

**Issue by huangnengCSU** [TimoLassmann/kalign#29]
Hi,
    I use kalign to perform MSA for DNA sequence. I used the parameter `kalign -i reads.fa -f clu  --tgpe 0.01 --gpo 0.2 --gpe 0.4`. The input fasta file is :
```
>1
GGGGGAAGGGGG
>2
GGGGAAGGGGG
>3
GGGGAAGGGGG
>4
GGGGAAGGGG
>5
GGGGGAAGGGGGG
>6
GGGGGAAGGGG
>7
GGGGGAAGGGGGA
>8
GGGGGAAGGGGGG
>9
GGGGGAAGGGGGG
>10
GGGGAAGTTG
>11
A
>12
GGGGGGAAGGGGG
>13
GGGGGAAGGGGGG
>14
GGGAGT
>15
GGGGAAGGGGG
```
The figure below is the alignment result of `clustalw.aln`. How can I adjust the parameter to get the similar alignment result as clustalw.
![image](https://user-images.githubusercontent.com/28866823/148319956-0b77c237-8a81-4f51-8d23-e37a7c3677de.png)

Best,
Neng

**Comment by TimoLassmann** [comment]
Hi, I added alignment types to version 3.3.4. The dna alignment type uses standard substitution, mismatch and gap penalties and will produce a sensible alignment in the case above.
