### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by tseemann** [TimoLassmann/kalign#3]
needed for brew and conda packaging

**Comment by TimoLassmann** [comment]
Done.

**Comment by tseemann** [comment]
Unfortunately, because you are using submodules, the release that github produces is incapable of building the software offline. You need to make your own .tgz and drag/upload it onto the releases panel. It's annoying i know.

**Comment by tseemann** [comment]
UPDATE: i see you ditched the submodule :)
