### ISSUE TITLE
Many unwanted log messages are printed to stderr when using kalign as a library

### ISSUE THREAD

**Issue by jeizenga** [TimoLassmann/kalign#36]
These messages are potentially confusing for users of downstream applications that incorporate kalign. The problem seems to come from this line:
https://github.com/TimoLassmann/kalign/blob/main/lib/src/aln_run.c#L915
Which escapes the quiet mode parameter that's set here:
https://github.com/TimoLassmann/kalign/blob/main/lib/src/aln_wrap.c#L28

**Comment by TimoLassmann** [comment]
Well spotted! I removed the line in aln_run in the latest commit.
