### ISSUE TITLE
Turning AVX2 on or off, the program produces different outputs

### ISSUE THREAD

**Issue by Shawdox** [TimoLassmann/kalign#39]
Hi, I tried to comment out the use of the bpm_256() function in the bpm.h file to make the program run as a non-AVX2 instruction and got a different result:
![image](https://github.com/TimoLassmann/kalign/assets/60968667/801f3a2e-ffff-447f-be49-ec53e1143e9e)
I would like to ask if this is normal and what are the possible causes of this problem, thank you very much!

**Comment by TimoLassmann** [comment]
Thanks for reporting. Could you send me the sequences (fewer the better)?

**Comment by Shawdox** [comment]
> Thanks for reporting. Could you send me the sequences (fewer the better)?

[ChR2_withou_AVX2.txt](https://github.com/TimoLassmann/kalign/files/11998473/ChR2_withou_AVX2.txt)
[ChR2_with_AVX2.txt](https://github.com/TimoLassmann/kalign/files/11998475/ChR2_with_AVX2.txt)
[input_ChR2.txt](https://github.com/TimoLassmann/kalign/files/11998476/input_ChR2.txt)

**Comment by Shawdox** [comment]
What did I try to do is making calc_distance() in sequence_distance.c run in serial:
![](https://github.com/TimoLassmann/kalign/assets/60968667/f7c07dd6-5423-4510-b427-433ab9417a85)
![](https://github.com/TimoLassmann/kalign/assets/60968667/ecd850bc-daef-4317-8d9d-175828985d2f)

**Comment by TimoLassmann** [comment]
I fixed this in version 3.4.0.
