### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by aebaci** [TimoLassmann/kalign#45]
Hi:

I wanted to use kalign to align CDS from eukaryote whole genomes ... 12 fasta files with an average of 20,000 sequences of variable length, average 1,200 bp, max 60,000 bp aprox. But I got the message "Segmentation fault (core dumped)" a few seconds after pressing enter to run the command, with no other indication.

I tried at first using -n =90, then I reduced to 80, 50, 12 and 8, and not including that setting, along with the type, but all gave the same result.

Any advice? Thanks.

**Comment by TimoLassmann** [comment]
Which version are you using and could you send me the input file for testing?

**Comment by aadyotb** [comment]
Hi @TimoLassmann, I also noticed some segfaults with kalign 3.4.0 a while back. Here's a fasta file of ~1800 proteins (uploaded as .txt) which causes issues, even with `-n 1` specified.
[kalign_bad.txt](https://github.com/user-attachments/files/17019856/kalign_bad.txt)

**Comment by aadyotb** [comment]
And here is one more example with much shorter sequences.
[kalign_bad2.txt](https://github.com/user-attachments/files/17048405/kalign_bad2.txt)

**Comment by TimoLassmann** [comment]
Hi,
On my machine I can align both sets of sequences without any problems. Try:
```
git clone https://github.com/TimoLassmann/kalign.git
cd kalign
mkdir build 
cd build
cmake ..
make 
./src/kalign ~/Downloads/kalign_bad.txt
```

**Comment by TimoLassmann** [comment]
Hi,
Looks like your files contain the standard output of the previous command:
```
tail -n 16 RHOPR_cds.fasta
GATCATGCACATCACTATAATAATCCTTACAGAGCATTGGACGAAACACTAGTACTGGAA
GAAGCTCTATTGGCTGTACTAGAAGCCGTCGACCAATCAGAAACGTTGATTGTCGTAACA
TCTGATCATTCGCACGTGCTCACAATGGGTGGATTGGCCACGCCCCGTGGGAATCCTATT
TTTGGTACAGACACAAAACTCTCCGACGTTGACGGTCTCCCATACTGGACACTGTTATAT
GGAAACGGCCCAGGCTATACAATGCCACGTGCTGTGCCAACAAATGTTAGCGGTTCAGAG
AAGAACGCCGTACATACTTCGGCCGTGCCAAGACAATGGGCTACACACGGCGGTGAAGAC
GTACCAGTGATGGCACAAGGCCCACTGGACATGGCATTGTTCTCTGGCACTATGGATCAA
ACTGTGGTGGCACATGCCATCGCTTATGCAGCGTGTCTGCCACCGTATTCTTATAGATGC
CAAAATAGTACACCGGCTGTATCGAAACCACAGATGTGTATACCAGATGAAAACAGTGTG
ACCAACGTAAAAGGTCGACCAGGACGTGGCGGTGTGGTGTTGGCTAGCTCGGTGATGTCC
GAAGACACGCCATCATTACAGCAGACGTCATCATCGTCCACGTCATCGTCGGAtggtgat
ggtggtggtggtagtggtAACAATAGTAATAGGTCGTCATCACCAATGAAAATCAGCCAA
TATATTCCAGCGCTTATTATTTTAATGGCGGCGATGGCTGCTGTCACCTGA
usage: /opt/miniconda3/envs/agat/bin/agat_sp_extract_sequences.pl -g RHOPR_sincont_ID.gff3 -f /home/antonella/DNA_Orthofinder/Rhodnius_pr.fasta -t cds
23727 cds converted in fasta.
Job done in 93 seconds
```
After removing these lines the alignment works. 
Thx, T

**Comment by aadyotb** [comment]
> Hi, On my machine I can align both sets of sequences without any problems. Try:
> 
> ```
> git clone https://github.com/TimoLassmann/kalign.git
> cd kalign
> mkdir build 
> cd build
> cmake ..
> make 
> ./src/kalign ~/Downloads/kalign_bad.txt
> ```

The current commit appears to have fixed the issue I was having. Can you create a new release 3.4.1 with the current main branch @TimoLassmann? Thanks.

**Comment by TimoLassmann** [comment]
Will do - thanks for reporting.
